import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  articles: defineTable({
    original_id: v.union(v.number(), v.null()),
    author_wpid: v.union(v.number(), v.null()),
    sponsored_position: v.union(v.number(), v.null()),
    title: v.string(),
    link: v.string(),
    source_link: v.union(v.string(), v.null()),
    content: v.string(),
    channel: v.union(v.number(), v.null()),
    channel_url: v.union(v.number(), v.null()),
    secondary_channel: v.union(v.number(), v.null()),
    secondary_channel_url: v.union(v.number(), v.null()),
    publish_date: v.string(),
    last_updated: v.string(),
    image_url: v.union(v.string(), v.null()),
    seo_meta: v.string(),
    video_url: v.union(v.string(), v.null()),
    video_title: v.union(v.string(), v.null()),
    audio_url: v.union(v.string(), v.null()),
    audio_file: v.union(v.string(), v.null()),
    transcript: v.union(v.string(), v.null()),
    white_paper_pdf: v.union(v.string(), v.null()),
    subtitle: v.string(),
    placefilter: v.union(v.number(), v.null()),
    rss_include: v.union(v.number(), v.null()),
    podcast_rss_include: v.union(v.number(), v.null()),
    fresh_finance_category: v.union(v.string(), v.null()),
    status: v.union(v.number(), v.null()),
    chart_url: v.union(v.string(), v.null()),
    other: v.string(),
    other_meta: v.string(),
    toolset_associations_contributor_post: v.union(v.string(), v.null()),
    wpcf_publishdate: v.union(v.number(), v.null()),
    author_id: v.union(v.number(), v.null()),
    embedding: v.optional(v.array(v.float64())),
    strapi_document_id: v.optional(v.string()), // For tracking Strapi articles across publish/unpublish cycles
  }).vectorIndex("by_embedding", {
    vectorField: "embedding",
    dimensions: 1536,
    filterFields: ["channel", "status"]
  }).index("by_author_wpid", ["author_wpid"]).index("by_author_id", ["author_id"]).index("by_channel", ["channel"]).index("by_original_id", ["original_id"]).index("by_strapi_document_id", ["strapi_document_id"]),

  contributors: defineTable({
    original_id: v.number(),
    name: v.string(),
    link: v.string(),
    join_date: v.string(),
    bio: v.string(),
    wp_user_id: v.number(),
    thumbnail_id: v.number(),
    contrib_img: v.string(),
    twitter: v.union(v.string(), v.null()),
    email: v.union(v.string(), v.null()),
    other: v.string(),
    other_meta: v.string(),
    published: v.number(),
    display_email: v.number(),
    display_linkedin: v.number(),
    display_twitter: v.number(),
    linkedin: v.union(v.string(), v.null()),
  }).index("by_original_id", ["original_id"]).index("by_wp_user_id", ["wp_user_id"]),
  // Add other tables here if needed
  channels: defineTable({
    original_id: v.union(v.number(), v.null()),
    title: v.union(v.string(), v.null()),
    slug: v.union(v.string(), v.null()),
    redirect: v.union(v.string(), v.null()),
    template: v.union(v.string(), v.null()),
    dataset: v.union(v.string(), v.null()),
    summary: v.union(v.string(), v.null()),
    channel_note: v.union(v.string(), v.null()),
    grid_placement: v.union(v.number(), v.null()),
    channel_notes: v.union(v.string(), v.null()),
    template_layout_id: v.union(v.number(), v.null())
  }).index("by_original_id", ["original_id"]),
}); 